FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
        wget squashfs-tools dosfstools parted udev grub2 grub-efi-amd64-signed shim-signed mtools ca-certificates && \
    rm -rf /var/lib/apt/lists/*
